### ISSUE TITLE
Displaying UTF-8 Characters?

### ISSUE THREAD

**Issue by blazer2k1** [jgmdev/lite-xl-encoding#2]
How do display UTF-8 Text just like in your plugin screenshots?

https://github.com/lite-xl/lite-xl/issues/1326#issuecomment-1382706593

**Comment by jgmdev** [comment]
It seems you already solved the issue with the fallback font, just in case this font contains a huge amount of glyphs https://savannah.gnu.org/projects/unifont/

**Comment by blazer2k1** [comment]
Thanks for the tip!
