### ISSUE TITLE
cannot load in windows 11

### ISSUE THREAD

**Issue by hugging** [jgmdev/lite-xl-encoding#3]
error log:

01/19/23 12:18:10 [ERROR] error loading module 'plugins.encodings' from file 'mypath\lite-xl\data/plugins\encodings.lua':
	mypath\lite-xl\data/plugins\encodings.lua:8: unexpected symbol near '<' at mypath\lite-xl\data/core/init.lua:1226

stack traceback:
[C]: in ?
[C]: in function 'require'
[C]: in function 'xpcall'
mypath\lite-xl\data/core/init.lua:1225: in function 'core.try'
mypath\lite-xl\data/core/init.lua:1013: in function 'core.load_plugins'
mypath\lite-xl\data/core/init.lua:793: in function 'core.init'
[string "local core..."]:8: in function <[string "local core..."]:2>
[C]: in function 'xpcall'
[string "local core..."]:2: in main chunk

I have copied "encoding.x86_64-windows.dll" to my libraries directory("$HOME/.config/lite-xl/libraries/"), also tried copying it to "mypath/lite-xl/data/libraries/", also tried renaming it to "encoding.dll".
Windows 11 22621.1105 + Lite XL v2.1.1 + Lite XL Encoding v1.1

**Comment by jgmdev** [comment]
Just tested the binaries on windows 11 and it works:

![2023-01-19_12:19:06](https://user-images.githubusercontent.com/1702572/213496070-e0e515a4-8d42-4494-bae1-80cbe01c03d6.png)

Did you installed the x86_64 version of Lite XL or the x86 version? Lite XL will fail to load the DLL if it was built for a different architecture than what Lite XL was built for.

In any case you have to put `encoding.x86_64-windows.dll` in `C:\Users\[YOUR_USER]\.config\lite-xl\libraries\encoding.dll`

and copy the lua plugin on `plugins/encodings.lua` to `C:\Users\[YOUR_USER]\.config\lite-xl\plugins\encodings.lua`

Also there is now a [package manager](https://github.com/lite-xl/lite-xl-plugin-manager) that will take care of installing a plugin and its dependencies for you.

**Comment by hugging** [comment]
Now it works. Thank you.
